version: '3.5'
services:
  app:
    build: .
    restart: always
    ports:
      - 3005:3000
    depends_on:
      - db
    networks:
      - mynetwork
    command: 'npm start'
  db:
    image: mongo
    restart: always
    expose:
      - 27017
    ports:
      - 2718:27017
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
